'use client';

import { Bug, Compass, Lock } from 'lucide-react';
import { useSessionManager } from '@/features/session/hooks/use-session-manager';
import { WelcomeScreen } from './welcome-screen';
import { ActiveSessionView } from './active-session-view';
import DebugOverlay from '@/shared/components/debug-overlay';
import { testApiConnection } from '@/features/ai/services/chat-service';

export function SessionContainer() {
  const { state, actions } = useSessionManager();

  const renderContent = () => {
    if (state.status === 'insecure-context') {
        return (
            <div className="flex flex-col items-center gap-4 text-center">
                <Lock className="w-10 h-10 text-red-400" />
                <h2 className="text-lg font-medium text-slate-200">Insecure Connection</h2>
                <p className="text-sm text-slate-400 max-w-xs">
                    Microphone access is disabled on insecure connections. Please use `localhost` or a secure `https` connection to use Aether.
                </p>
            </div>
        );
    }

    if (state.status === 'unsupported') {
      return (
        <div className="flex flex-col items-center gap-4 text-center">
          <Compass className="w-10 h-10 text-yellow-400" />
          <h2 className="text-lg font-medium text-slate-200">Browser Not Supported</h2>
          <p className="text-sm text-slate-400 max-w-xs">
            Aether uses advanced speech technologies that are not available in your current browser. Please use Google Chrome or Microsoft Edge for the best experience.
          </p>
        </div>
      );
    }
    
    if (state.status === 'running') {
        return (
            <ActiveSessionView 
                voiceState={state.voiceState} 
                permissionStatus={state.permissionStatus}
                onToggleListening={actions.toggleListening}
                onToggleMute={actions.toggleMute}
                onRetryPermission={actions.onRetryPermission}
            />
        );
    }

    return <WelcomeScreen onBegin={actions.handleStartSession} />;
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-slate-950 text-slate-100 p-4">
      <DebugOverlay isOpen={state.isDebugOpen} onClose={actions.toggleDebug} onTestApi={testApiConnection} />
      
      <div className="absolute inset-0 bg-gradient-to-b from-indigo-950/20 to-slate-950 pointer-events-none" />

      <div className="z-10 max-w-md w-full text-center space-y-8">
        
        <div>
          <h1 className="text-4xl font-thin tracking-tight text-indigo-200">Aether</h1>
          <p className="text-slate-400 text-sm mt-2">Empathetic Voice Companion</p>
        </div>

        <div className="min-h-[200px] flex flex-col items-center justify-center">
            {renderContent()}
        </div>

        <div className="mt-12 p-4 border-t border-slate-800">
          <p className="text-xs text-slate-500 leading-relaxed">
            <span className="font-bold text-slate-400">Disclaimer:</span> Aether is an AI demo. It is not a healthcare provider. 
            Responses are generated by AI and may be inaccurate. 
            If you are in crisis, please contact local emergency services immediately.
          </p>
          <button 
            onClick={actions.toggleDebug} 
            className={`mt-2 text-[10px] flex items-center gap-1 transition-colors ${state.isDebugOpen ? 'text-indigo-400' : 'text-slate-700 hover:text-slate-500'}`}
          >
             <Bug size={10} /> {state.isDebugOpen ? 'Debug On' : 'Debug Mode'}
          </button>
        </div>
      </div>
    </main>
  );
}
